sudo: required
services: 
  - docker
  
# Build fastapi image that can be tested  
before-install:
  - docker build -t morciu/docker-multi-py-test -f ./server/Dockerfile.dev ./server

script:
  - docker run morciu/docker-multi-py-test python ./server/app/test.py

after_success:
  - docker build -t morciu/sub-db ./db
  - docker build -t morciu/sub-frontend ./frontend
  - docker build -t morciu/sub-nginx ./nginx
  - docker build -t morciu/sub-server ./server
