version: '3'
services:
  frontend:
    image: "morciu/sub-frontend"
    # mem_limit: 256m
    hostname: frontend
  nginx:
    restart: always
    image: "morciu/sub-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
      - api
  api:
    image: "morciu/sub-server"
    mem_limit: 128m
    hostname: api
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_HOST=$MYSQL_HOST
    # ports:
    #   - "5000:5000"
    restart: always