version: '3'
services:
  db:
    build:
      dockerfile: Dockerfile.dev
      context: ./db
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - frontend
      - api
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db