name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and test FastAPI image
      run: |
        docker build -t morciu/docker-multi-py-test -f ./server/Dockerfile.dev ./server
        docker run morciu/docker-multi-py-test python -m unittest discover

    - name: Build other images
      run: |
        docker build -t morciu/sub-db ./db
        docker build -t morciu/sub-frontend ./frontend
        docker build -t morciu/sub-nginx ./nginx
        docker build -t morciu/sub-server ./server
    
    - name: Login and Push to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push morciu/sub-db
        docker push morciu/sub-frontend
        docker push morciu/sub-nginx
        docker push morciu/sub-server
